CREATE TABLE classroom (
  guid BINARY(16) NOT NULL COMMENT 'Guid for adding class',
  name VARCHAR(255) NOT NULL,
  year SMALLINT NOT NULL,
  remark VARCHAR(255) NOT NULL,
  section SMALLINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (guid),
  UNIQUE KEY (name, year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;